### ISSUE TITLE
Password Validation Failed! on RTL v0.3.1 

### ISSUE THREAD

**Issue by openoms** [ShahanaFarooqui/RTL#143]
**Describe the bug**
Cannot log in to RTL v0.3.1 
Gives error:
Message:Authentication Failed! 
Error:Password Validation Failed! 

**To Reproduce**
Update RTL on Raspiblitz:
Uninstall RTL from services menu
`nano ~/config.scripts/bonus.RTL.sh`
edit line 54 to `git reset --hard v0.3.1`
reinstall RTL from Services menu and reboot
visit RTL address and type RPC password

**Expected behavior**
login

**Actual behavior**
Gives error:
ERROR
Message:Authentication Failed! 
Error:Password Validation Failed! 

**Your environment**
* version of `lnd` 0.6.1-beta
* operating system RaspiBlitz V1.0 and v1.2 Raspbian/DietPi/Ubuntu
* bitcoind v0.18.0

**Additional context**
No problem with v0.3.0 in the same environment

Could be a problem with:
Security feature:
Hashing of the plain text password stored in the conf files (requires server restart) ?

**Comment by saubyk** [comment]
Hi @openoms  can you please confirm what's the authtype setting in RTL.conf for you?

**Comment by openoms** [comment]
> Hi @openoms can you please confirm what's the authtype setting in RTL.conf for you?

Thanks for the quick reply. My RTL.conf:

admin@HC1:~$ cat RTL/RTL.conf 
[Authentication]
macaroonPath=
nodeAuthType=DEFAULT
lndConfigPath=/mnt/hdd/lnd/lnd.conf
rtlPass=

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
bitcoindConfigPath=
enableLogging=true
port=3000
lndServerUrl=https://localhost:8080/v1

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login

**Comment by saubyk** [comment]
@openoms we are investigating this. This may be a bug on our end.

**Comment by ShahanaFarooqui** [comment]
@openoms, Thanks for raising the issue. 'DEFAULT' authentication type broke when we implemented Sha256 hashing in the last release. It has been fixed and released with v0.3.2. 

Please get the latest version to fix this issue. Closing it for now, please feel free to reopen if needed.

**Comment by openoms** [comment]
Thank you fro the lightning quick solution. Love to be able to add private channels with a click!

**Comment by goodc0re** [comment]
I am still facing this same error but on v0.4.4-beta. 

Message:Authentication Failed!
Error:Password Validation Failed!

This is on a raspibliz 1.2 running litecoin mainnet and LND 0.6.0-beta

I already reset the TLS certs and macaroons. 
 

$ cat RTL/RTL.conf
[Authentication]
macaroonPath=
nodeAuthType=DEFAULT
lndConfigPath=/mnt/hdd/lnd/lnd.conf
rtlPass=

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
channelBackupPath=C:\RTL\backup
bitcoindConfigPath=
enableLogging=true
port=3000
lndServerUrl=https://localhost:8080/v1

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login

**Comment by saubyk** [comment]
Hi @goodc0re can you please confirm if your `lnd.conf` has the `rpcpass` field?

**Comment by goodc0re** [comment]
Yes it does have it:

[Litecoind]
litecoind.rpchost=127.0.0.1
litecoind.rpcuser=raspibolt
litecoind.rpcpass=mypassword
litecoind.zmqpubrawblock=tcp://*:28332
litecoind.zmqpubrawtx=tcp://*:28333

**Comment by ShahanaFarooqui** [comment]
It seems strange that authentication is failing after all this information in place. Were you able to login before with the same setup and it broke with 0.4.4 version or is it the first time setup? Can you also please share the rtl .log file, it might have some more information.

**Comment by goodc0re** [comment]
It worked fine before upgrading to raspiblitz 1.2 with an older version of RTL, yes. 

```
$ tail -n 1000 RTL.log 

INFO: Config Setup Variable => NODE_SETUP: SINGLE
INFO: Config Setup Variable => PORT: 3000
INFO: Config Setup Variable => LND_SERVER_URL: https://localhost:8080/v1
INFO: Config Setup Variable => MACAROON_PATH: /home/admin/.lnd/data/chain/litecoin/mainnet
INFO: Config Setup Variable => NODE_AUTH_TYPE: DEFAULT
INFO: Config Setup Variable => LND_CONFIG_PATH: /mnt/hdd/lnd/lnd.conf
INFO: Config Setup Variable => RTL_CONFIG_PATH: /home/admin/RTL
INFO: Config Setup Variable => BITCOIND_CONFIG_PATH: undefined
INFO: Config Setup Variable => CHANNEL_BACKUP_PATH: C:\RTL\backup
INFO: Config Setup Variable => RTL_SSO: 0
INFO: Config Setup Variable => RTL_COOKIE_PATH: 
INFO: Config Setup Variable => LOGOUT_REDIRECT_LINK: /login
ERROR: Authenticate(89) => Password Validation Failed!
```

**Comment by saubyk** [comment]
Hi @goodc0re

Looks like we are not handling the rpc password for litecoind section of the `lnd.conf` file.

For now, can you try with the auth type as CUSTOM and setting a password in `RTL.conf`.

**Comment by goodc0re** [comment]
That solution works!

**Comment by ShahanaFarooqui** [comment]
@goodc0re, we are closing the issue now. Thanks.

**Comment by klnit** [comment]
Hi,
I have the same problem:
ERROR: Authenticate(38) => Password Validation Failed!

Set up a fresh env on Win 8 Enterprise:
bitcoin-0.19.1-win64
lnd-windows-amd64-v0.10.0-beta
RTL-0.7.0 (also tried current master)

What password do I have to provide? LND wallet password?

**Comment by ShahanaFarooqui** [comment]
@klnit It depends upon your RTL config settings, RTL version, authentication type etc. Please check the setup configuration documentation or share your rtl config file after masking sensitive information.

**Comment by klnit** [comment]
Thanks, the initial password works. Sorry
