### ISSUE TITLE
Preventing access_key to show up in browser history

### ISSUE THREAD

**Issue by NicolasDorier** [ShahanaFarooqui/RTL#58]
Problem:

Access_key shows up in the browser history, giving access to LND wallet to anybody having access to url.

Solution:

We got the same problem with spark-wallet to which @shesek fixed with this commit 
 https://github.com/shesek/spark-wallet/commit/d1a637ed581ac667c24a3bf96cdffd24517270d9

Can you implement the same?

**Comment by shesek** [comment]
The reason I implemented the double-redirect-with-a-`<meta>`-tag trick was to get the [`SameSite=strict`](https://www.owasp.org/index.php/SameSite) cookie sent properly when the pairing URL is opened from a different origin (i.e. when manually copy-pasted to the URL bar, opened from a QR scanning app, linked to from a different website origin, etc). Without this, the browser would set the cookie, but refuse to send it along to the page its redirected to.

But if you don't expect cross-origin requests to the pairing URL (BTCPay should be running on the same origin) or if you don't have `SameSite` set for your cookies (you really should though), you don't need the double-redirect thing, a simple `301` redirect to the main page should be enough to prevent the access key from being saved to history.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier @shesek I am trying to understand the solution you have implemented for this.
As far as i understood, the above solution is refreshing the client page/document. But, how is it preventing it to show up in the browser history? It will not be the first opened url but the entry will still be there in the history stack. Or am i missing something here?

And, if this is correct, we are already redirecting the page after getting authenticated and the url with access key shows at the third number on the history.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I think this is because of the `return res.redirect(301, 'redir')``

**Comment by ShahanaFarooqui** [comment]
But that redirect is sending refresh meta tag in the response, which will refresh the page. Pardon my lack of knowledge on this topic but how is it preventing the browser to save the access key with its initial request? The only thing that we are able to observe is that the last request will not have the access_key but the initial request will.

**Comment by NicolasDorier** [comment]
I think (did not tried it), it is because HTTP 301 tells to the browser to not remember this URL (because it is just a permanent redirect).

The meta hack is explained by shesek:

> But if you don't expect cross-origin requests to the pairing URL (BTCPay should be running on the same origin) or if you don't have `SameSite` set for your cookies (you really should though), you don't need the double-redirect thing, a simple `301` redirect to the main page should be enough to prevent the access key from being saved to history.

So it seems you don't really need it.

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/53281026-87bc4d00-3765-11e9-8589-2ddfe7238197.png)
 :(

**Comment by NicolasDorier** [comment]
Your redirect is 304, not 301. This might be why.

**Comment by NicolasDorier** [comment]
Let me try one more time. If you say you already do the redirect, maybe the accesskey from my history come from one of my tests. I need to clean the history and try again one sec.

**Comment by ShahanaFarooqui** [comment]
Our node server is returning pre-build angular SPA index.html on root url and currently we do not have any idea on returning it with 301 :(. So, let us do some more research on preventing SPA's query params to be saved in browser history and get back to you.

**Comment by NicolasDorier** [comment]
just configure the node server to do the redirect instead of returning the SPA if there is the access-key parameter. It should do the trick.

**Comment by ShahanaFarooqui** [comment]
That is the problem :(, node server is returning pre-build app on '/rtl/' path but this access key is being passed to another POST request at '/rtl/api/authenticate'.

**Comment by NicolasDorier** [comment]
so what about I do a GET with the access key to /rtp/api/authenticate instead?

**Comment by ShahanaFarooqui** [comment]
That can do the trick, it will return jwt token which can then be passed to the application.

**Comment by ShahanaFarooqui** [comment]
Or you can expose an api for rtl to get cookie value through that API and respond only if the requester is rtl app. i hope it makes sense :)

**Comment by ShahanaFarooqui** [comment]
authenticate is a POST request, just in case you want to try.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I don't want a POST request because I want the user to be able to click on a link to go.
Also, I want them to be able to scan the QR code on btcpay page to browse to it.
What I mean is, if the `/rtl` is handled by node by servicing the app, we can use a separate path GET `rtl/api/authenticate?access_key=` to do the redirect 301 to `/rtl` after setting the cookie.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier Latest release 0.2.9 has updated to redirect the access key url to root. The initial btcpayserver should open the RTL app with 'http://localhost:3000/rtl/api/authenticate/<your-access-key-value>' link now. This link will redirect the api to '/rtl/' root with 301 response code and then pre-build UI will also be returned to browser with response code 301. 

![image](https://user-images.githubusercontent.com/23240721/53292041-90883f80-37b4-11e9-90f5-06f7b930597e.png)

**Comment by ShahanaFarooqui** [comment]
But unfortunately, we were unable to get anything good out of this change. We can still see the access key in Chrome and Firefox's browser histories but RTL is unable to authenticate on Firefox now.

Yesterday, I read somewhere that with https/nginx, 301 response doesn't get cached. So, i pushed the changes for testing with btcpayserver. Please test the app on all the browsers, we might have to undo these changes.

From SSO's point, we would recommend btcpayserver to maintain a cookie and share it with its on-boarded applications, whenever the application requests for it.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui BTCPay does not use RTL internally at all. Also for mobile user, it is important that the way to connect is just by a QR code. I will test today. I think @shesek is trying something as well.

**Comment by NicolasDorier** [comment]
(reviewed your PR, and it seems to me to do something way more complicated that it should be, will check)

**Comment by NicolasDorier** [comment]
With 0.2.9 I don't manage to authenticate at all.

**Comment by saubyk** [comment]
Hi @NicolasDorier can we have a quick call with you to discuss this?
I sent you twitter DM as well. I feel we will have to resolve quicker with a short dialogue.
Please let us know. Thanks.

**Comment by NicolasDorier** [comment]
yeah

**Comment by NicolasDorier** [comment]
where call? on slack? skype?

**Comment by NicolasDorier** [comment]
Actually the failure to log might be unrelated to this version. Same issue with .7, but it was working before.

**Comment by NicolasDorier** [comment]
@shesek are you playing with it? It seems we can't find a good solution to prevent browser caching :(

**Comment by NicolasDorier** [comment]
Ping @shesek doing it on https://github.com/ShahanaFarooqui/RTL/pull/61 it seems that redirect 301 get cached by browser. This mean that if spark login expire, the user won't be able to log in anymore without clearing browser cache. Trying to use `cache-control` to prevent this.

**Comment by shesek** [comment]
How about just adding some random string to the pairing URL to bust the cache? i.e. `http://instance.btcpay/RTL/authenticate?access-key=[....]&r=[random]`

**Comment by NicolasDorier** [comment]
Because it assume the user refreshed the page. Changing the `cache-control` worked.

**Comment by shesek** [comment]
So simply `Cache-Control: no-cache` did the trick?

**Comment by NicolasDorier** [comment]
@shesek yes, see https://github.com/ShahanaFarooqui/RTL/pull/61/files#diff-09bb577980201a4eb86b5ac2607c290eR12

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier @shesek I tried cache control header setting yesterday but it didn’t work at my end. Tried sending the response with 303 and 307 also but those are also being saved in browser history.

Front end code is at ‘Shahanafarooqui/RTLFullApplication. But, the first request is sent by browser, so I was unable to catch the cookie from the request.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I am quite sure it works. Everytimes I refresh I get no `cached from disk` from chrome dev.

The first request to `/authenticate/cookie` is giving you back the cookie to the client, you should be able to use this from browser side, to send with the POST /authenticate.

**Comment by NicolasDorier** [comment]
Let's move it https://github.com/ShahanaFarooqui/RTL/pull/61

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier I merged the code in my full application and working on sending the cookie from front end with authentication API. I will merge and publish the code asap.

I just tested the browser history and even after getting cache-conrtol header, it is still saving the link. But, it might work with https, so i will publish this again with front end updates.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier we merged the code to send the access key value from client side with authenticate API. The authentication is working now but my browser is saving the history with no-cache setting :(

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui probably because you already cached from before

**Comment by NicolasDorier** [comment]
we are almost there, still not working, but your request is correct. Diving into it.

**Comment by ShahanaFarooqui** [comment]
oh ok, just FYI, client request is sending the access_key value in the req body. So changed authentication.js to read it from their not from the cookie.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui you reverted my changes on https://github.com/ShahanaFarooqui/RTL/commit/81a6a36fba8f7ebf787e0c457d50bacaee4802cd

**Comment by NicolasDorier** [comment]
Yeah but no. This is not correct, it should read from cookie

**Comment by ShahanaFarooqui** [comment]
I did not reverted your changes, all other changes are their but had to change authentication.js to read from body. because, i am unable to catch the cookie at the client side, so i read the access key from browser url and sent that into request body.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I checked the queries, and you are sending the cookie in the request client side. If you put back what you reverted, it will work.

**Comment by ShahanaFarooqui** [comment]
sure, reverting it.

**Comment by ShahanaFarooqui** [comment]
Reverted authentication.js changes. published 2.9 again. 

Please let me know if you want me to revert my whole commit.

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui I am trying to get it to work, it is near I can feel it! :)
That said, actually, I think the front did not needed change. This is a `HttpOnly` cookie, so this is normal the front end do not have access to it. But nevermind. Now server side, I don't have the cookie. 

Trying to find out why, problem on my side now,

**Comment by NicolasDorier** [comment]
@ShahanaFarooqui you can make a new release after https://github.com/ShahanaFarooqui/RTL/pull/62

**Comment by NicolasDorier** [comment]
This works as :)

**Comment by ShahanaFarooqui** [comment]
Published this change with v0.2.10.
